import { useState } from 'react'
import { Link, NavLink, Route, Routes, useParams } from 'react-router-dom'
import { ArrowUpRight, ChevronRight, Download, Menu, Moon, Search, Sun, X } from 'lucide-react'
import { certificates, projects, skills } from './data'
import './App.css'

const API = import.meta.env.VITE_API_URL || (import.meta.env.DEV ? '' : 'https://meta-certificate.onrender.com')
const asset = (url) => url?.startsWith('/uploads/') ? `${API}${url}` : url
const SITE_URL = import.meta.env.VITE_SITE_URL || 'https://samiya-certificate.netlify.app'
const SectionLabel = ({ number, children }) => <div className="section-label"><span>{number}</span>{children}<i /></div>
const Logo = () => <Link className="logo" to="/">A<span>.</span></Link>

function Navbar({ dark, setDark }) {
  const [open, setOpen] = useState(false)
  const links = [['Home', '/'], ['About', '/#about'], ['Skills', '/#skills'], ['Projects', '/#projects'], ['Certificates', '/certificates']]
  return <header className="navbar"><Logo /><nav className={open ? 'nav-links open' : 'nav-links'}>{links.map(([label, href]) => href.startsWith('/#') ? <a key={label} href={href} onClick={() => setOpen(false)}>{label}</a> : <NavLink key={label} to={href} onClick={() => setOpen(false)}>{label}</NavLink>)}</nav><div className="nav-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button className="menu-button icon-button" onClick={() => setOpen(!open)} aria-label="Open menu">{open ? <X size={19} /> : <Menu size={19} />}</button></div></header>
}
function Hero() { return <section className="hero-wrap"><div className="hero-copy"><div className="availability"><span /> Available for new opportunities</div><h1>Building digital<br /><em>experiences</em> with intent.</h1><p className="hero-intro">Hi, I'm Abduraxim — a frontend developer crafting modern, responsive and interactive web experiences with clean code and creative design.</p><div className="hero-buttons"><a href="#projects" className="button button-dark">View my projects <ArrowUpRight size={17} /></a><Link to="/certificates" className="button button-light">View certificates <ChevronRight size={17} /></Link></div></div><div className="hero-art"><div className="art-grid" /><div className="code-window"><div className="window-bar"><span /><span /><span /><small>portfolio.jsx</small></div><pre><b>const</b> developer = {'{'}<br />  name: <i>'Abduraxim'</i>,<br />  focus: <i>'frontend'</i>,<br />  status: <i>'creating'</i><br />{'}'}</pre></div><div className="portrait"><div className="portrait-ring"></div><span>Frontend<br />Developer</span></div><div className="float-chip chip-react">React <b>↗</b></div><div className="float-chip chip-ui">UI / UX <b>✦</b></div></div></section> }
function About() { return <section id="about" className="section about-section"><SectionLabel number="01">About me</SectionLabel><div className="about-grid"><h2>Curious by nature,<br /><span>precise by craft.</span></h2><div className="about-body"><p>I'm a passionate frontend developer who enjoys transforming ideas and designs into modern, responsive and interactive websites.</p><p className="muted">I care about the small things: a thoughtful transition, a clear component, a page that feels effortless to use.</p><div className="about-facts"><div><strong>2+</strong><span>Years learning<br />& building</span></div><div><strong>50+</strong><span>Projects<br />completed</span></div></div></div></div></section> }
function Skills() { return <section id="skills" className="section skills-section"><SectionLabel number="02">My skills</SectionLabel><div className="section-heading"><h2>Tools for <span>making things.</span></h2></div><div className="skills-grid">{skills.map(([name, desc, icon]) => <div className="skill-card" key={name}><div className="skill-icon">{icon}</div><div><h3>{name}</h3><p>{desc}</p></div><ArrowUpRight size={17} /></div>)}</div></section> }
function Projects() { return <section id="projects" className="section projects-section"><SectionLabel number="03">Selected work</SectionLabel><div className="section-heading"><h2>Featured <span>projects.</span></h2></div><div className="projects-grid">{projects.map(project => <article className={`project-card ${project.tone}`} key={project.title}><div className="project-art"><span className="project-number">{project.number}</span><div className="project-frame"><div className="frame-top"><span /><span /><span /></div><div className="frame-lines"><b /><b /><b /><i /></div></div></div><div className="project-info"><div><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div><a href="https://github.com" className="round-link"><ArrowUpRight size={18} /></a></div></article>)}</div></section> }
function CertificateCard({ item, onOpen }) { return <article className={`certificate-card accent-${item.accent}`}><button className="certificate-paper" onClick={() => onOpen(item)}><span className="paper-mark">{item.mark}</span><span className="paper-title">Certificate<br /><b>of achievement</b></span><span className="paper-seal">✦</span></button><div className="certificate-info"><div><h3>{item.title}</h3><p>{item.organization} <span>·</span> {item.date}</p></div><button className="small-arrow, small-arrow" onClick={() => onOpen(item)} aria-label="Open certificate"><ArrowUpRight className='ar1' size={20} /><ArrowUpRight className='ar2' size={20} /></button></div></article> }
function CertificatesPage({ items, onOpen }) { const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const categories = ['All', 'Programming', 'Frontend', 'English', 'Other']; const filtered = items.filter(item => (category === 'All' || item.category === category) && `${item.title} ${item.organization}`.toLowerCase().includes(query.toLowerCase())); return <main className="certificates-page"><div className="certificates-hero"><SectionLabel number="/">The archive</SectionLabel><h1>My <em>certificates.</em></h1><p>A collection of certificates and achievements from my learning journey.</p></div><div className="certificate-toolbar"><div className="search-box"><Search size={18} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search certificates..." /></div><div className="filter-list">{categories.map(item => <button className={category === item ? 'active' : ''} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="archive-grid">{filtered.map(item => <CertificateCard item={item} onOpen={onOpen} key={item.id} />)}</div>{filtered.length === 0 && <div className="empty-state">No certificates found.</div>}</main> }
function PDFViewer({ item, close }) { if (!item) return null; const pdf = asset(item.pdf); const image = asset(item.thumbnail); return <div className="viewer-backdrop"><div className="viewer"><div className="viewer-head"><div><span className="eyebrow">Certificate preview</span><h2>{item.title}</h2></div><button className="icon-button" onClick={close} aria-label="Close"><X size={20} /></button></div><div className="pdf-page">{image ? <img className="certificate-image" src={image} alt={item.title} /> : <iframe src={pdf} title={item.title} />}</div><div className="viewer-actions"><a className="button button-dark" href={pdf} download><Download size={16} /> Download PDF</a><a className="text-link" href={pdf} target="_blank" rel="noreferrer">Open PDF <ArrowUpRight size={15} /></a></div></div></div> }
function Verify() { const { id } = useParams(); const item = certificates.find(certificate => String(certificate.id) === id); return <main className="verification-page"><div className="verification-card"><span className={item ? 'verify-status' : 'verify-status invalid'}>{item ? 'Verified certificate' : 'Certificate not found'}</span>{item && <><h1>{item.title}</h1><p>This certificate belongs to <strong>Abduraxim</strong> and was issued by {item.organization} in {item.date}.</p>{item.thumbnail && <img className="verification-image" src={item.thumbnail} alt={item.title} />}<a className="button button-dark" href={item.pdf} download><Download size={16} /> Download certificate</a><p className="verification-url">QR URL: {SITE_URL}/certificate/{item.id}</p></>}</div></main> }
function App() { const [dark, setDark] = useState(false); const [selected, setSelected] = useState(null); return <div className={dark ? 'app dark' : 'app'}><Navbar dark={dark} setDark={setDark} /><Routes><Route path="/" element={<><main><Hero /><About /><Skills /><Projects /><section className="section certificates-preview"><SectionLabel number="04">Credentials</SectionLabel><div className="section-heading"><h2>A few things I've <span>earned.</span></h2></div><div className="certificate-grid">{certificates.slice(0, 3).map(item => <CertificateCard item={item} onOpen={setSelected} key={item.id} />)}</div></section></main></>} /><Route path="/certificates" element={<CertificatesPage items={certificates} onOpen={setSelected} />} /><Route path="/certificate/:id" element={<Verify />} /><Route path="/certificates/:id" element={<Verify />} /></Routes><PDFViewer item={selected} close={() => setSelected(null)} /></div> }
export default App
