export const certificates = [
  {
    id: 1,
    title: 'Frontend Developer',
    organization: 'Meta IT School',
    date: '2026',
    category: 'Frontend',
    pdf: '/certificates/Frontend-CR.png',
    thumbnail: '/certificates/Frontend-CR.png',
    accent: 'cyan',
    mark: 'F',
  },
  {
    id: 2,
    title: 'Backend Developer',
    organization: 'Meta IT School',
    date: '2026',
    category: 'Programming',
    pdf: '/certificates/Backend-CR.png',
    thumbnail: '/certificates/Backend-CR.png',
    accent: 'cerulean',
    mark: 'B',
  },
  {
    id: 3,
    title: 'Active Participant Certificate',
    organization: 'Target International School',
    date: '14.08.2026',
    category: 'Other',
    pdf: '/certificates/Target-CR.png',
    thumbnail: '/certificates/Target-CR.png',
    accent: 'coral',
    mark: 'A',
  },
  {
    id: 4,
    title: '30% Discount on IT Courses',
    organization: 'Target International School',
    date: '14.08.2026',
    category: 'Other',
    pdf: '/certificates/Target-Bonus-CR.png',
    thumbnail: '/certificates/Target-Bonus-CR.png',
    accent: 'cyan',
    mark: '30%',
  },
  {
    id: 5,
    title: 'StartUp Certificate',
    organization: 'RoboCode - Turon University',
    date: '05.03.2026',
    category: 'Other',
    pdf: '/certificates/RoboCode-CR.png',
    thumbnail: '/certificates/RoboCode-CR.png',
    accent: 'cerulean',
    mark: 'R',
  },
]

export const skills = [
  ['HTML', 'Semantic, accessible structure', '◈'],
  ['CSS', 'Motion, layout and polish', '✦'],
  ['JavaScript', 'Thoughtful interaction logic', 'JS'],
  ['React', 'Composable product interfaces', '⚛'],
  ['Tailwind CSS', 'Fast, consistent systems', '◫'],
  ['Git & GitHub', 'Clear, collaborative workflow', '⌘'],
  ['GSAP', 'Motion with intention', '↗'],
  ['Responsive Design', 'Built for every screen', '▣'],
]

export const projects = [
  {
    title: 'Noma — Creative Studio',
    description: 'A bold editorial site for a small creative studio.',
    tags: ['React', 'GSAP'],
    tone: 'project-sun',
    number: '01',
  },
  {
    title: 'Form — Design System',
    description: 'A focused component library for teams that care about detail.',
    tags: ['React', 'CSS'],
    tone: 'project-ink',
    number: '02',
  },
  {
    title: 'Lumen — Product Landing',
    description: 'A luminous product experience with a clear path to action.',
    tags: ['JavaScript', 'UI/UX'],
    tone: 'project-blue',
    number: '03',
  },
]
